name: "Dependency Review"

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
