name: Deploy to GH Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
      - name: Dump version
        run: |
          node -v
          npm --version
          git --version
      - run: npm ci
      - run: npm build
        env:
          NODE_ENV: production

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
