name: Code checks

on:
  push:
    branches: [$default-branch]
  pull_request:

env:
  NODE_VERSION: 20.11
  # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
  A11Y_HOST: http://localhost:4173 # Vite preview default url:port

jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run format:check:all
      - run: npm run lint:check:all
      - run: npm run build --if-present

  pa11y-axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run preview & npx wait-on $A11Y_HOST
      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y $A11Y_HOST \
            --runner axe \
            --runner htmlcs \
            --ignore 'nested-interactive'
            --ignore 'WCAG2AA.Principle1.Guideline1_4.1_4_3.G18'
