name: Lint, format and build checks

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run format:check:all

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run lint:check:all

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
